defaults:
  - override hydra/job_logging: custom

data:
  image_width: 640
  image_height: 360

  pct_train_split: 0.8  # rest is used for testing
  n_in_features: 3      # 3 for taking a single frame, 9 for taking 3 frames, etc.

hyperparameters:
  continue_training_from_weights: true # if false a new model will train from scratch
  path_to_weights: models/model_good.pt                # path to the weights, should be in the /models/ dir
  seed: 1312
  batch_size: 2
  epochs: 15
  learning_rate: 1.0

wandb:
  mode: disabled # "disabled" or "online" or "offline"
  project_name: tennis-court-tracking
  train_log_interval: 10
  validation_log_interval: 10